kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - pull_request

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
  - name: build
    image: yarnpkg/node-yarn
    commands:
      - node -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install && yarn build
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/cache/drone
