kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - pull_request

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone:/cache
  - name: build
    image: yarnpkg/node-yarn
    commands:
      - node -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install && yarn build
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone:/cache
